version: 1.2
workflows:
   - name: pgsc_calc
     subclass: WDL
     primaryDescriptorPath: /pgsc_calc.wdl
     testParameterFiles:
       - /pgsc_calc.json
   - name: pgsc_calc_prepare_genomes
     subclass: WDL
     primaryDescriptorPath: /pgsc_calc_prepare_genomes.wdl
     testParameterFiles:
       - /pgsc_calc_prepare_genomes.json
   - name: calc_scores
     subclass: WDL
     primaryDescriptorPath: /calc_scores.wdl
     